name: 'AMI creation'
description: 'AMI creation of different Servers'
inputs:
  script-input:  # id of input
    description: 'Input of shell script'
    required: true
    default: '..'
runs:
  using: "composite"
  steps:
    # - run: echo Hello ${{ inputs.who-to-greet }}.
    #   shell: bash
    # - id: random-number-generator
    #   run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
    #   shell: bash
    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    #   shell: bash
    # - run: goodbye.sh
    #   shell: bash

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Test configuration of AWS CLI
      run: |
        aws --version
        aws configure list | grep region | awk '{print $2}'
      shell: bash

    - name: Checkout
      uses: actions/checkout@v2 

    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "1.8.5" # or `latest`

    - name: Run `packer init`
      id: init
      run: "packer init ${{ inputs.script-input }}"
      shell: bash

    - name: Run `packer validate`
      id: validate
      run: "packer validate ${{ inputs.script-input }}"
      shell: bash

    - name: Run `packer build`
      id: build
      run: "packer build ${{ inputs.script-input }}"
      shell: bash