name: jekins
on: [push]
jobs:
  aws-cli:
   name: AWS cI Setup 
   runs-on: ubuntu-20.04
   steps:
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
     - name: Test configuration of AWS CLI
       run: |
         aws --version
         aws configure list | grep region | awk '{print $2}'
   